version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Install Meteor
          command: "curl https://install.meteor.com | sh"
      - run:
          name: Install dependencies
          command: "npm install"
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths: node_modules

  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run:
          name: Install Meteor
          command: "curl https://install.meteor.com | sh"
      - run:
          name: Install mup
          command: "npm install mup@1.3.4"
      - run: ./node_modules/mup/index.js deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - circle2.0
